# Generated by Django 5.1.1 on 2024-09-27 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='active',
            field=models.BooleanField(default=False, verbose_name='Activa'),
        ),
    ]
