# Generated by Django 5.1.1 on 2024-09-28 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_task_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='active',
            field=models.BooleanField(blank=True, default=False, verbose_name='Activa'),
        ),
    ]
